### ISSUE TITLE
Create app skeleton using Create React App

### ISSUE THREAD

**Issue by infojunkie** [meedan/check-mark#1]
Use the official FB tool to create the app skeleton: https://github.com/facebookincubator/create-react-app

**Comment by mazhang2718** [comment]
I've used a Mozilla repo in the past (https://github.com/mdn/webextensions-examples/tree/master/react-es6-popup) to scaffold a React-based web extension - would it be okay if we used this instead of the FB tool? The main difference seems to be that tests aren't as easily integrated, but it does use tools like webpack and babel.

**Comment by infojunkie** [comment]
I'd prefer to use the FB tool, which we are hoping to standardize across our projects.
